name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Package
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb1-dev \
            libxrandr-dev \
            libxss-dev \
            libgtk-3-dev \
            libglib2.0-dev \
            libcairo-gobject2 \
            libgtk-layer-shell-dev \
            libdbus-1-dev

      - name: Build release binary
        run: cargo build --release

      - name: Build documentation
        run: cargo doc --all-features --no-deps

      - name: Create Linux release package
        if: runner.os == 'Linux'
        run: |
          mkdir release
          cp target/release/egui_opengl_app release/
          cp README.md release/
          chmod +x release/egui_opengl_app
          zip -r egui_opengl_app-linux.zip release/

      - name: Create Windows release package
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          mkdir release
          copy "target\release\egui_opengl_app.exe" release\
          copy README.md release\
          Compress-Archive -Path release\* -DestinationPath egui_opengl_app-windows.zip

      - name: Upload Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: egui_opengl_app-linux
          path: egui_opengl_app-linux.zip
          retention-days: 90

      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: egui_opengl_app-windows
          path: egui_opengl_app-windows.zip
          retention-days: 90

      - name: Upload documentation
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: target/doc/
          retention-days: 30